/**
 * Seed data for CampusFind AI.
 * Mirrors sql/seed.sql and provides enriched sample data for demo mode.
 */

export const INITIAL_STUDENTS = [
  {
    StudentID: 1,
    Name: 'Navika Kapoor',
    Email: 'navika@campus.edu',
    Phone: '9876543210',
    Department: 'Computer Science',
    Year: 3,
    Hostel: 'Hostel A',
  },
  {
    StudentID: 2,
    Name: 'Parthvi Sharma',
    Email: 'parthvi@campus.edu',
    Phone: '9876543211',
    Department: 'Computer Science',
    Year: 3,
    Hostel: 'Hostel B',
  },
  {
    StudentID: 3,
    Name: 'Rohan Mehta',
    Email: 'rohan@campus.edu',
    Phone: '9876543212',
    Department: 'Electronics',
    Year: 2,
    Hostel: 'Hostel C',
  },
];

export const INITIAL_ADMIN = {
  AdminID: 1,
  Name: 'Campus Security Admin',
  Email: 'admin@campus.edu',
};

export const INITIAL_LOST_ITEMS = [
  {
    LostID: 1,
    ItemName: 'Water Bottle',
    Category: 'Accessories',
    Brand: 'Milton',
    Color: 'Blue',
    Description: 'Steel water bottle with a dented cap, has a college sticker on it',
    DateLost: '2026-09-10',
    LostLocation: 'Central Library, 2nd Floor',
    Status: 'Open',
    StudentID: 1,
    AdminID: 1,
    studentName: 'Navika Kapoor',
    imageUrl: null,
  },
  {
    LostID: 2,
    ItemName: 'Wired Earphones',
    Category: 'Electronics',
    Brand: 'boAt',
    Color: 'Black',
    Description: 'Black wired earphones in a small pouch left on the table',
    DateLost: '2026-09-12',
    LostLocation: 'Cafeteria & Canteen',
    Status: 'Open',
    StudentID: 2,
    AdminID: null, // Pending admin verification
    studentName: 'Parthvi Sharma',
    imageUrl: null,
  },
  {
    LostID: 3,
    ItemName: 'Campus ID & Lanyard',
    Category: 'Documents & Cards',
    Brand: 'University RFID',
    Color: 'Blue',
    Description: 'Student ID card in a transparent sleeve with an orange Campus lanyard',
    DateLost: '2026-09-14',
    LostLocation: 'Engineering Block Auditorium',
    Status: 'Open',
    StudentID: 2,
    AdminID: 1,
    studentName: 'Parthvi Sharma',
    imageUrl: null,
  },
  {
    LostID: 4,
    ItemName: 'Scientific Calculator',
    Category: 'Electronics',
    Brand: 'Casio fx-991EX',
    Color: 'Black',
    Description: 'Classwiz scientific calculator with my initials P.S. scratched on the back cover',
    DateLost: '2026-09-15',
    LostLocation: 'Maths Lecture Hall 3',
    Status: 'Matched',
    StudentID: 2,
    AdminID: 1,
    studentName: 'Parthvi Sharma',
    imageUrl: null,
  },
  {
    LostID: 5,
    ItemName: 'Navy Blue Backpack',
    Category: 'Bags & Backpacks',
    Brand: 'Wildcraft',
    Color: 'Navy Blue',
    Description: 'Contains lecture notebooks, yellow pencil case and water flask',
    DateLost: '2026-09-16',
    LostLocation: 'Sports Complex Badminton Court',
    Status: 'Open',
    StudentID: 3,
    AdminID: null,
    studentName: 'Rohan Mehta',
    imageUrl: null,
  }
];

export const INITIAL_FOUND_ITEMS = [
  {
    FoundID: 1,
    ItemName: 'Steel Bottle',
    Category: 'Accessories',
    Brand: 'Milton',
    Color: 'Blue',
    Description: 'Found a blue steel bottle near the reading hall entrance with a sticker',
    DateFound: '2026-09-11',
    FoundLocation: 'Central Library Entrance',
    Status: 'Open',
    StudentID: 3,
    AdminID: 1,
    studentName: 'Rohan Mehta',
    imageUrl: null,
  },
  {
    FoundID: 2,
    ItemName: 'Earphones',
    Category: 'Electronics',
    Brand: 'boAt',
    Color: 'Black',
    Description: 'Picked up black wired earphones near the canteen tables',
    DateFound: '2026-09-12',
    FoundLocation: 'Cafeteria & Canteen',
    Status: 'Open',
    StudentID: 3,
    AdminID: 1,
    studentName: 'Rohan Mehta',
    imageUrl: null,
  },
  {
    FoundID: 3,
    ItemName: 'Student RFID Card',
    Category: 'Documents & Cards',
    Brand: 'University RFID',
    Color: 'Blue',
    Description: 'Found near auditorium staircase, handed over to security desk',
    DateFound: '2026-09-14',
    FoundLocation: 'Auditorium Steps',
    Status: 'Open',
    StudentID: 1,
    AdminID: 1,
    studentName: 'Navika Kapoor',
    imageUrl: null,
  },
  {
    FoundID: 4,
    ItemName: 'Casio Calculator',
    Category: 'Electronics',
    Brand: 'Casio',
    Color: 'Black',
    Description: 'fx-991EX calculator found on bench after afternoon session',
    DateFound: '2026-09-15',
    FoundLocation: 'Maths Lecture Hall 3',
    Status: 'Claimed',
    StudentID: 1,
    AdminID: 1,
    studentName: 'Navika Kapoor',
    imageUrl: null,
  },
  {
    FoundID: 5,
    ItemName: 'House & Room Keys',
    Category: 'Keys',
    Brand: 'Godrej',
    Color: 'Silver / Brass',
    Description: 'Set of 3 keys with a wooden elephant keychain ring',
    DateFound: '2026-09-16',
    FoundLocation: 'Hostel B Gate',
    Status: 'Open',
    StudentID: 2,
    AdminID: null, // Pending admin verification
    studentName: 'Parthvi Sharma',
    imageUrl: null,
  },
  {
    FoundID: 6,
    ItemName: 'Black Backpack',
    Category: 'Bags & Backpacks',
    Brand: 'Wildcraft',
    Color: 'Black',
    Description: 'Black backpack found near sports pavilion bench, padded straps and side water bottle pocket',
    DateFound: '2026-09-17',
    FoundLocation: 'Sports Complex Bench',
    Status: 'Open',
    StudentID: 1,
    AdminID: 1,
    studentName: 'Navika Kapoor',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
  }
];

export const INITIAL_MATCH_RECORDS = [
  {
    MatchID: 1,
    LostID: 1,
    FoundID: 1,
    MatchDate: '2026-09-11 14:30:00',
    MatchStatus: 'Pending',
    score: 0.94,
    lostItem: INITIAL_LOST_ITEMS[0],
    foundItem: INITIAL_FOUND_ITEMS[0],
  },
  {
    MatchID: 2,
    LostID: 2,
    FoundID: 2,
    MatchDate: '2026-09-12 18:20:00',
    MatchStatus: 'Pending',
    score: 0.91,
    lostItem: INITIAL_LOST_ITEMS[1],
    foundItem: INITIAL_FOUND_ITEMS[1],
  },
  {
    MatchID: 3,
    LostID: 3,
    FoundID: 3,
    MatchDate: '2026-09-14 11:15:00',
    MatchStatus: 'Confirmed',
    score: 0.88,
    lostItem: INITIAL_LOST_ITEMS[2],
    foundItem: INITIAL_FOUND_ITEMS[3],
  }
];

export const INITIAL_CLAIMS = [
  {
    ClaimID: 1,
    ClaimDate: '2026-09-12 16:45:00',
    ClaimStatus: 'Pending',
    VerificationNotes: 'Awaiting student to show college ID card at Security Post 1',
    StudentID: 1,
    FoundID: 1,
    studentName: 'Navika Kapoor',
    foundItem: INITIAL_FOUND_ITEMS[0],
  },
  {
    ClaimID: 2,
    ClaimDate: '2026-09-15 17:00:00',
    ClaimStatus: 'Approved',
    VerificationNotes: 'Serial number and scratched initials matched. Item successfully handed over.',
    StudentID: 2,
    FoundID: 4,
    studentName: 'Parthvi Sharma',
    foundItem: INITIAL_FOUND_ITEMS[3],
  }
];

export const INITIAL_NOTIFICATIONS = [
  {
    NotificationID: 1,
    Message: '✨ We found a 94% match for your Milton Water Bottle!',
    Date: '2026-09-11 14:35:00',
    ReadStatus: false,
    StudentID: 1,
    MatchID: 1,
    type: 'match',
  },
  {
    NotificationID: 2,
    Message: '✨ AI detected a 91% match for your boAt Wired Earphones!',
    Date: '2026-09-12 18:22:00',
    ReadStatus: false,
    StudentID: 2,
    MatchID: 2,
    type: 'match',
  },
  {
    NotificationID: 3,
    Message: '🎉 Your claim for Casio Calculator fx-991EX has been Approved by Security Admin.',
    Date: '2026-09-15 17:05:00',
    ReadStatus: true,
    StudentID: 2,
    MatchID: null,
    type: 'claim_approved',
  },
  {
    NotificationID: 4,
    Message: '🛡️ Your lost report for Campus ID & Lanyard has been verified by Admin.',
    Date: '2026-09-14 09:30:00',
    ReadStatus: true,
    StudentID: 2,
    MatchID: null,
    type: 'admin_verified',
  }
];

export const CAMPUS_CATEGORIES = [
  'All Categories',
  'Accessories',
  'Electronics',
  'Documents & Cards',
  'Bags & Backpacks',
  'Keys',
  'Books & Stationery',
  'Clothing',
  'Others'
];

export const CAMPUS_LOCATIONS = [
  'Central Library',
  'Cafeteria & Canteen',
  'Engineering Block A',
  'Engineering Block B',
  'Science Block',
  'Sports Complex',
  'Auditorium',
  'Hostel A',
  'Hostel B',
  'Hostel C',
  'Admin Building',
  'Campus Grounds'
];
